Resources:
  WeatherAppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WeatherAppData
      AttributeDefinitions:
        - AttributeName: Date
          AttributeType: S
      KeySchema:
        - AttributeName: Date
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
