name: Deploy GetWeather Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/get_weather/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      - name: Install dependencies
        run: |
          pip install -r lambda/get_weather/requirements.txt -t lambda/get_weather/

      - name: Zip Lambda
        run: |
          cd lambda/get_weather
          zip -r ../get_weather_lambda.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: GetWeatherFunction
          zip_file: lambda/get_weather_lambda.zip
